### ISSUE TITLE
Gorillib 0.5.0 is broken

### ISSUE THREAD

**Issue by kornypoet** [infochimps-labs/gorillib#8]
A simple line that used to work (taken from the internal documentation in `lib/gorillib/model/base.rb)`:

``` ruby
class Person
  include Gorillib::Model

  field :name,   String,  :doc => 'Full name of person'
  field :height, Float,   :doc => 'Height in meters'
end
```

now breaks with an apocryphal error message:

```
ArgumentError: visibility must be one of [:public, :private, :protected]: got nil
    from /Users/travis/.rvm/gems/ruby-1.9.2-p290/gems/gorillib-0.5.0/lib/gorillib/model/named_schema.rb:30:in `define_meta_module_method'
    from /Users/travis/.rvm/gems/ruby-1.9.2-p290/gems/gorillib-0.5.0/lib/gorillib/model/schema_magic.rb:103:in `define_attribute_reader'
    from /Users/travis/.rvm/gems/ruby-1.9.2-p290/gems/gorillib-0.5.0/lib/gorillib/model/field.rb:102:in `inscribe_methods'
    from /Users/travis/.rvm/gems/ruby-1.9.2-p290/gems/gorillib-0.5.0/lib/gorillib/model/schema_magic.rb:27:in `field'
```

Looking at the documentation (`README.md`, the classes in `lib/gorillib/model`) yields no answer. Is this a "feature" or a bug?

**Comment by kornypoet** [comment]
Turns out this affects previous versions of `Gorillib` as well. It has something to do with the order of `require` statements, as I have experienced different behavior based on who/what order `Gorillib` classes are loaded.

**Comment by mrflip** [comment]
can you give an example of a pathological include order? things look
reasonable from my quick double-check.

flip

**Comment by kornypoet** [comment]
@hustonhoburg suggested a scenario in which `ActiveSupport` is conflicting with `Gorillib` definitions. I can confirm that when `active_support` is NOT required, `Gorillib::Model` acts normally, when `active_support` IS required, `Gorillib::Model` becomes angry. Closing the issue.
